---

- hosts: blog_server
  roles:
  - role: common
  - { role: traefik-website, website: atariblog }
  - { role: traefik-website, website: watchblog }
  - { role: traefik-website, website: librespeed }
  - { role: traefik-website, website: kuma }
  - { role: traefik-website, website: forsale }
  become: yes
