version: '3.8'
  
services:
  watchblog:
    image: eagle243/private:watchblog
    networks:
      - traefik_net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.watchblog-http.entrypoints=http"
        - "traefik.http.routers.watchblog-http.rule=Host(`watches.unixdude.net`)"
        - "traefik.http.routers.watchblog-http.middlewares=watchblog-http"
        - "traefik.http.routers.watchblog-http.service=watchblog"
        - "traefik.http.middlewares.watchblog-http.redirectscheme.scheme=https"
        - "traefik.http.middlewares.watchblog-http.redirectscheme.permanent=true"
        - "traefik.http.routers.watchblog.entrypoints=https"
        - "traefik.http.routers.watchblog.rule=Host(`watches.unixdude.net`)"
        - "traefik.http.routers.watchblog.tls=true"
        - "traefik.http.routers.watchblog.tls.certresolver=dns-digitalocean"
        - "traefik.http.routers.watchblog.middlewares=watchblog"
        - "traefik.http.routers.watchblog.service=watchblog"
        - "traefik.http.middlewares.watchblog.compress=true"
        - "traefik.http.services.watchblog-http.loadbalancer.server.port=80"
        - "traefik.http.services.watchblog.loadbalancer.server.port=443"
        - "traefik.docker.network=traefik_net"

networks:
  traefik_net:
    external: true
    name: traefik_net
