---

- name: "Disable root ssh"
  replace: 
    path: /etc/ssh/sshd_config
    regexp: 'PermitRootLogin yes'
    replace: 'PermitRootLogin no'
  notify: restart sshd

- name: "Disable password ssh"
  replace: 
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication yes'
    replace: 'PasswordAuthentication no'
  notify: restart sshd
