version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    volumes:
      - /usr/local/docker/minecraft/world:/worlds/world
      - /usr/local/docker/minecraft/data:/data
