---

- name: Install common packages
  apt:
    name: ['screen', 'tcsh', 'mlocate', 'net-tools', 'vim', 'telnet', 'pciutils', 'git', 'mtr', 'traceroute', 'ntp', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    state: latest

- name: Set default editor
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim.basic
