---

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: "Install pip dependencies"
  pip:
    name:
      - docker

- name: Init a new swarm with default parameters (not home)
  community.docker.docker_swarm:
    advertise_addr: "{{ ansible_eth0.ipv4.address }}"
    state: present
  ignore_errors: yes
  when: home_dns_fix is not defined or home_dns_fix == "False"

- name: Init a new swarm with default parameters (home)
  community.docker.docker_swarm:
    state: present
  ignore_errors: yes
  when: home_dns_fix is defined or not home_dns_fix | bool

- name: Log into docker hub
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
    email: "{{ docker_email }}"

- name: Add user to docker group
  user:
    name: "{{ adduser }}"
    groups: docker
    append: yes
