---

- name: "Ensure /usr/local/docker directory exists"
  file:
    path: /usr/local/docker
    state: directory

- name: "Ensure /usr/local/docker/letsencrypt directory exists"
  file:
    path: /usr/local/docker/letsencrypt
    state: directory

- name: "Copy traefik docker-compose file"
  ansible.builtin.template:
    src: docker-compose-traefik.yml
    dest: /usr/local/docker/docker-compose-traefik.yml
    mode: '0644'

- name: "Install pip dependencies"
  pip:
    name:
      - jsondiff
      - pyyaml

- name: Set up dynamic config
  include_tasks: "copy_traefik_config_file.yml"
  when: publish_traefik is defined and publish_traefik | bool

- name: Start traefik
  docker_stack:
    state: present
    name: traefik
    compose:
      - /usr/local/docker/docker-compose-traefik.yml
  become: yes
