version: '3.8'
  
services:
  librespeed:
    image: ghcr.io/linuxserver/librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      #- PASSWORD=PASSWORD
      #- CUSTOM_RESULTS=false #optional
      #- DB_TYPE=sqlite #optional
      #- DB_NAME=DB_NAME #optional
      #- DB_HOSTNAME=DB_HOSTNAME #optional
      #- DB_USERNAME=DB_USERNAME #optional
      #- DB_PASSWORD=DB_PASSWORD #optional
      #- DB_PORT=DB_PORT #optional
    volumes:
      - /usr/local/docker/librespeed-config:/config
    deploy:
      labels:
        - "traefik.http.routers.librespeed.entrypoints=web"
        - "traefik.http.routers.librespeed.rule=Host(`librespeed.unixdude.net`)"
        - "traefik.http.routers.librespeed.middlewares=librespeed-https"
        - "traefik.http.routers.librespeed.service=librespeed"
        - "traefik.http.middlewares.librespeed.redirectscheme.scheme=https"
        - "traefik.http.middlewares.librespeed.redirectscheme.permanent=true"
        - "traefik.http.routers.librespeed-https.entrypoints=web-secured"
        - "traefik.http.routers.librespeed-https.rule=Host(`librespeed.unixdude.net`)"
        - "traefik.http.routers.librespeed-https.tls=true"
        - "traefik.http.routers.librespeed-https.middlewares=librespeed-https"
        - "traefik.http.routers.librespeed-https.service=librespeed"
        - "traefik.http.middlewares.librespeed-https.compress=true"
        - "traefik.http.services.librespeed.loadbalancer.server.port=80"
        - "traefik.http.services.librespeed-https.loadbalancer.server.port=443"
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik
